<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

namespace qbank_questiongen\local;

use cm_info;
use lesson;
use qbank_questiongen\form\story_form;
use question_bank;
use stdClass;

/**
 * Question generator class.
 *
 * @package    qbank_questiongen
 * @copyright  2025 ISB Bayern
 * @author     Philipp Memmel
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
class question_generator {
    /** @var string[] Text mimetypes that can be read directly from file contents. */
    const TEXT_MIMETYPES = ['text/plain', 'text/html', 'text/csv'];

    /**
     * Creates an instance of the question_generator.
     */
    public function __construct(
        /** @var int The id of the context the question_generator is called from. */
        private readonly int $contextid
    ) {
    }

    /**
     * Generate a question by using an external LLM.
     *
     * @param stdClass $dataobject of the stored processing data from qbank_questiongen DB table extended with example data.
     * @return stdClass|string object containing information about the generated question or string containing an error message
     *  in case of an error occurred and no question could be generated
     */
    public function generate_question(stdClass $dataobject, bool $sendexistingquestionsascontext): stdClass|string {
        global $CFG, $DB;
        require_once($CFG->dirroot . '/question/engine/bank.php');

        // Build primer.
        $primer = $dataobject->primer;
        $story = $dataobject->story;
        $instructions = $dataobject->instructions;
        $example = $dataobject->example;

        $storyprompt = '';
        $questiontextsinqbankprompt = '';
        $generatedquestiontext = '';

        $provider = get_config('qbank_questiongen', 'provider');
        if ($provider === 'local_ai_manager') {
            $systemprompt =
                '## PRIMER' . "\n"
                . $primer . "\n\n"
                . '## INSTRUCTIONS' . "\n"
                . $instructions . "\n\n"
                . '## EXAMPLE MOODLE XML QUESTION' . "\n"
                . $example;

            // Append existing questions to the prompt if option is chosen.
            if ($sendexistingquestionsascontext) {
                $questionidsincategory = question_bank::get_finder()->get_questions_from_categories([$dataobject->category], null);
                if (!empty($questionidsincategory)) {
                    [$insql, $inparams] = $DB->get_in_or_equal($questionidsincategory);
                    $rs = $DB->get_recordset_select('question', "id $insql", $inparams);
                    $questiontextsinqbankcat = [];
                    foreach ($rs as $record) {
                        $questiontextsinqbankcat[] = [
                            'title' => $record->name,
                            'question_text' => strip_tags($record->questiontext),
                        ];
                    }
                    $rs->close();
                    $questiontextsinqbankprompt = '## ALREADY EXISTING QUESTIONS' . "\n"
                        . 'The question that will be generated by you has to be as different '
                        . 'as possible from all of the following questions in this JSON string: "'
                        . json_encode($questiontextsinqbankcat) . '"';

                    $systemprompt .= "\n\n" . $questiontextsinqbankprompt;
                }
            }
            // Until here we were building the system prompt. The next strings will be put into the user prompt.
            // So no leading line feeds necessary here.
            $modeheader = '## QUESTION GENERATION MODE - ';
            switch ($dataobject->mode) {
                case story_form::QUESTIONGEN_MODE_TOPIC:
                    $storyprompt =
                        $modeheader . 'TOPIC' . "\n"
                        . 'Create a question about the following topic. Use your own training data to generate it:' . "\n"
                        . $story;
                    break;
                case story_form::QUESTIONGEN_MODE_STORY:
                case story_form::QUESTIONGEN_MODE_COURSECONTENTS:
                    $storyprompt =
                        $modeheader . 'CONTENTS' . "\n"
                        . 'Create a question from the following contents. '
                        . 'Only use this contents and do not use any training data:' . "\n"
                        . '### START OF USER PROVIDED CONTENT' . "\n"
                        . $story . "\n"
                        . '### END OF USER PROVIDED CONTENT';
                    break;
            }

            $messages = [
                [
                    'sender' => 'system',
                    'message' => $systemprompt,
                ],
                [
                    'sender' => 'user',
                    'message' => $storyprompt,
                ],
            ];

            [
                'generatedquestiontext' => $generatedquestiontext,
                'errormessage' => $errormessage,
            ] = $this->retrieve_llm_response($messages);
        }

        if (!empty($errormessage)) {
            return $errormessage;
        }

        // We return a whole question object containing all the generated data. This can be used for unit tests or logging.
        $question = new stdClass();
        $question->primer = $primer;
        $question->instructions = $instructions;
        $question->example = $example;
        $question->storyprompt = $storyprompt;
        $question->questiontextsinqbankprompt = $questiontextsinqbankprompt;
        $question->text = $generatedquestiontext;

        return $question;
    }

    /**
     * Generates the story to send to the LLM based on the content from course activites.
     *
     * @param array $courseactivities list of course module ids
     * @return string text extracted from the activities that can be send as context to the external AI system
     */
    public function create_story_from_cms(array $courseactivities): string {
        global $CFG;
        require_once($CFG->dirroot . '/question/editlib.php');

        [, $firstcm] = get_module_from_cmid(reset($courseactivities));
        $modinfo = get_fast_modinfo($firstcm->course);
        $story = '';
        $cms = array_filter($modinfo->get_cms(), fn($cm) => in_array($cm->id, $courseactivities));

        foreach ($cms as $cm) {
            if (!in_array($cm->id, $courseactivities)) {
                continue;
            }
            if (!$this->is_cm_supported($cm)) {
                debugging('Course module with id ' . $cm->id . ' is currently not supported');
                continue;
            }
            $story .= $this->extract_content_from_cm($cm);
        }
        return $story;
    }

    /**
     * Returns if a course module is supported by the question generator.
     *
     * @param cm_info $cm the cm_info object of the course module
     * @return bool true if extracting content from the course module is supported, false otherwise
     */
    public static function is_cm_supported(cm_info $cm): bool {
        if (in_array($cm->modname, ['page', 'label', 'lesson', 'book', 'folder'])) {
            return true;
        }
        if ($cm->modname === 'resource') {
            $context = \context_module::instance($cm->id);
            $fs = get_file_storage();
            $files = $fs->get_area_files($context->id, 'mod_resource', 'content', 0, 'sortorder DESC, id ASC', false);
            $file = reset($files);
            if (empty($file)) {
                return false;
            }
            $extractor = \core\di::get(\local_ai_content\document_extractor::class);
            return $extractor->is_file_supported($file);
        }
        return false;
    }

    /**
     * For a given course module, extract the content as plain text.
     *
     * @param cm_info $cm the cm_info object of the course module
     * @return string the content of the course module as plain text.
     * @throws \coding_exception if the course module is not supported
     */
    public function extract_content_from_cm(cm_info $cm): string {
        global $CFG, $DB;
        // TODO Eventually also respect course module descriptions and title?
        $content = '';
        $instance = $cm->get_instance_record();
        switch ($cm->modname) {
            case 'page':
                $content = $instance->content;
                break;
            case 'label':
                $content = $instance->intro;
                break;
            case 'resource':
                $context = \context_module::instance($cm->id);
                $fs = get_file_storage();
                $files = $fs->get_area_files($context->id, 'mod_resource', 'content', 0, 'sortorder DESC, id ASC', false);
                $file = reset($files);
                if (!empty($file)) {
                    $content = $this->extract_content_from_file($file);
                }
                break;
            case 'folder':
                $context = \context_module::instance($cm->id);
                $fs = get_file_storage();
                $files = $fs->get_area_files($context->id, 'mod_folder', 'content', 0, 'id ASC', false);
                $filecontents = [];
                foreach ($files as $file) {
                    if (!empty($file)) {
                        $filecontent = trim($this->extract_content_from_file($file));
                        if ($filecontent !== '') {
                            $filecontents[] = $filecontent;
                        }
                    }
                }
                // Will later be converted to proper line breaks.
                $content = implode("<br/><br/>", $filecontents);
                break;
            case 'lesson':
                require_once($CFG->dirroot . '/mod/lesson/locallib.php');
                $lesson = lesson::load($instance->id);
                $pages = $lesson->load_all_pages();
                $pagescontents = [];
                foreach ($pages as $page) {
                    // We must not use $page->get_contents() here because it requires having the $PAGE object set up properly for
                    // the lesson course module which we do not have.
                    $pagescontents[] = trim($page->properties()->contents);
                }
                $content = implode("<br/><br/>", $pagescontents);
                break;
            case 'book':
                require_once($CFG->dirroot . '/mod/book/locallib.php');
                $book = $DB->get_record('book', ['id' => $instance->id]);
                $chapters = book_preload_chapters($book);
                $chaptercontents = [];
                foreach ($chapters as $chapter) {
                    $chaptercontents[] = $chapter->title . "<br/>" . $chapter->content;
                }
                $content = implode("<br/><br/>", $chaptercontents);
                break;
            default:
                throw new \coding_exception('Unsupported course module/course module type - cmid: ' . $cm->id . ', ' .
                    $cm->modname);
        }

        return empty($content) ? '' : self::format_extracted_cm_content($content);
    }

    /**
     * Extracts content from pdf or image files.
     *
     * Delegates extraction to local_ai_content\document_extractor.
     *
     * @param \stored_file $file The file to send
     * @return string the extracted content as text
     */
    public function extract_content_from_pdf_or_image(\stored_file $file): string {
        $extractor = \core\di::get(\local_ai_content\document_extractor::class);
        return $extractor->extract_text_from_file($file, $this->contextid, $file->get_userid() ?: null, 'qbank_questiongen');
    }

    /**
     * Extract content from a file.
     *
     * Extraction failures propagate to the caller.
     *
     * @param \stored_file $file The file to process.
     * @return string The extracted content.
     */
    private function extract_content_from_file(\stored_file $file): string {
        if (in_array($file->get_mimetype(), self::TEXT_MIMETYPES)) {
            return $file->get_content();
        }

        $extractor = \core\di::get(\local_ai_content\document_extractor::class);
        try {
            return $extractor->extract_text_from_file($file, $this->contextid, $file->get_userid() ?: null, 'qbank_questiongen');
        } catch (\moodle_exception $exception) {
            throw new questiongen_exception(
                $exception->errorcode,
                $exception->module,
                $exception->link,
                $exception->a,
                $exception->debuginfo
            );
        }
    }

    /**
     * Helper function to format the extracted content.
     *
     * It basically removes all HTML tags and converts line breaks into text line breaks.
     *
     * @param string $content the content to format
     * @return string the formatted content
     */
    public static function format_extracted_cm_content(string $content): string {
        $content = trim($content);
        return html_to_text($content, 0, false);
    }

    /**
     * Helper function to retrieve the generated question XML from the external LLM.
     *
     * @param array $messages a standardized messages array containing the "conversation" with the LLM
     * @return string[] array with keys 'generatedquestionxml' and 'errormessage'. If 'errormessage' is empty retrieving
     *  was successful, otherwise it contains an error message.
     */
    public function retrieve_llm_response(array $messages): array {
        // TODO Implement different backend(s). It's only local_ai_manager for now.
        $return = [
            'generatedquestiontext' => '',
            'errormessage' => '',
        ];
        $manager = new \local_ai_manager\manager('questiongeneration');
        $lastmessage = array_pop($messages);
        $result = $manager->perform_request(
            $lastmessage['message'],
            'qbank_questiongen',
            $this->contextid,
            ['conversationcontext' => $messages]
        );
        if ($result->get_code() === 200) {
            $return['generatedquestiontext'] = $result->get_content();
            mtrace('Question generation successful. The external LLM returned: ');
            mtrace($result->get_content());
        } else {
            mtrace('Question generation failed. The external LLM returned code ' . $result->get_code() . ':');
            mtrace($result->get_errormessage());
            if (!empty($result->get_debuginfo())) {
                mtrace($result->get_debuginfo());
            }
            // Return the error message.
            $result['errormessage'] = $result->get_errormessage();
        }
        return $return;
    }
}
